[gsheets]
type = "service_account"
project_id = "streamlit-connect-406919"
private_key_id = "b2b91b1c82bd99f569d5de272619dee55215a377"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCg7Hw3xRN/E/Ha
huCSo5vZaPBvrwDB+V7LdoOVY9vmOnm1x4H2ZwAo8V5Lml9wNHPgiF3xyw3uRcus
uoZuojjggDONfq6y2/gEYdEzQ7r6Iz8H2Xg/Epgbva8Fxg1HBP9KedMU55uB4BRs
UiH/TDOHUaaBRc3WnoNDmUh9rc3ot7tS36p6hs4uFgfWzPTIPfeF6gLjY1saILMM
5UwdwMynexqDdETt79B40Lfqs0kwNPX/99r28BB6v22gpHTEOuEt8ewv4HM8scya
NOSxraxufljsqZ4j/VbgSSwXXAjK3Ui0OD/YbZwPfg0jam/3IkFtct93XDpHMt2P
Q+ofO12jAgMBAAECggEABUDjJ0DwS4A/r4Yis7bSoizaWJMKf8qfzR2f2xMo/SGg
ko4iUIR5TVzf2rD996BGvihFhNy/pi0yIn/uXpM+LxoQVMizdFRZCu+UkEtgQcU/
zAZN9iUpwRIWsiYOjeh8WxaSDQconPtPP2AJCxgWQI8qU+MO/rgrCdxpsOypIbU8
kDVuzfsmkbw8cz8/dUsS5XKFBpbfe6ciirOq6qym/KIOxi4OFSVbsXCfLlYUl5/P
UXTcUf4NqXob7AzqzLhD1mIrs6u9kJyCDFvufEroXcuW93qyT91O31ZE55wp0ez5
DijhEe6j0eWmXw7A/oPvHVtTY0/0JNBZjHwGFuSvdQKBgQDLA/gVQ/+lKpE55bLy
kBGOsF3dEV2HVs1gcDEkxx1t2HgsX6jGiJ/95v1vRJo28AOeun70O+YFnbeGlww8
GPbMyXp3JVAORqdk5xnOe5e8NdDVBRWv72h/qKno0Z+mtnLDBt9CYZfEiVws0Suh
loDO3+lo7oSMe5D3OqHP1Zi5pwKBgQDK7EAQxCTbuxdrHAiiXx338B7oICtFMSdi
55UHh4I09JPXrR5So1wL6HoggoeFRhFHzdtIoBKE94B3Uj5wWgNXBaPHYdvO32rT
w2GU5e4iZFtXYpARE8gk2v4t7bjcmEy7BuqkOYwa0zF1gVBy7fNlHegj1kcVBmIj
+Ojeh8NDpQKBgQCivfPJWFE+3fi9KN1ihQsOD2OvK5SGQZcxj75VdSiqPbVYHPb2
798RcnIHGD9nes/sFiRfNQUXy26rfbpZEsoFMB30FP0v9IOL55ZQZ9MjFSDrIsBX
4NssOtC5yhDpW6hznraqSAGZk2NIqgUH69YmAGjjrRCkbQmwplfAe8GKUQKBgF2U
a8sPmWvXsOoNSJIQyVJA4w/rXekPzPkYkSqivFJNhCyPQo+blGRNdpytdW/pqyhw
77JjV4cIWK8uN2s6p5WnHStinqqdb7duv/6ZtqMXouP+qS+m7sLIVzW5Dmp0tdX+
T5EilND+Gi31T7NgtsEn9JkqRSeWBQZP0JxnAY6dAoGAPzTcI0bwKthZFqz7yLeY
Au650DVeCpdJ8X02McRXdpwvt+VwnvABA3TBXpQD+ZwNV4z75flEjz1Kmhb4oIbH
7SvB1SW48GWaicnYcsEdEm7rWUlJkMszVshzlr6UNR772JAknnBH06UBVqpJ1yVv
iroqZEbXhnOLongn93571ps=
-----END PRIVATE KEY-----"""
client_email = "hotel-service@streamlit-connect-406919.iam.gserviceaccount.com"
client_id = "108566213723713038670"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/hotel-service%40streamlit-connect-406919.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[app]
spreadsheet_key = "1ndVk4efZZN74serPvDpN6tcm2NamLqKlcYfz2-y156g"

